FROM karsten13/magicmirror:latest
COPY ./magic-mirror-server/config /opt/magic_mirror/config/
COPY ./magic-mirror-server/modules /opt/magic_mirror/modules/
COPY ./magic-mirror-server/css /opt/magic_mirror/css/