---
version: '3'
services:
  magicmirror:
    container_name: magic-mirror-server
    image: ${CUSTOM_CONTAINER_REGISTRY}/${GITHUB_ACTOR}/magic-mirror-server
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
    secrets:
      - OPEN_WEATHER_MAP_LOCATION
      - OPEN_WEATHER_MAP_LOCATION_ID
      - OPEN_WEATHER_MAP_API_KEY
      - CALENDAR_ICS_URL_PATH
    ports:
      - 80:80

secrets:
  OPEN_WEATHER_MAP_LOCATION:
    environment: ${OPEN_WEATHER_MAP_LOCATION}
  OPEN_WEATHER_MAP_LOCATION_ID:
    environment: ${OPEN_WEATHER_MAP_LOCATION_ID}
  OPEN_WEATHER_MAP_API_KEY:
    environment: ${OPEN_WEATHER_MAP_API_KEY}
  CALENDAR_ICS_URL_PATH:
    environment: ${CALENDAR_ICS_URL_PATH}
