FROM karsten13/magicmirror:latest
WORKDIR /app
COPY ./config /opt/magic_mirror/config
COPY ./modules /opt/magic_mirror/modules
ADD ./css/custom.css /opt/magic_mirror/css/custom.css
ADD ./css/main.css /opt/magic_mirror/css/main.css