name: Deploy to magic mirror

env:
  AZURE_WEBAPP_NAME: magic-mirror-server
  DOCKER_IMAGE: bastilimbach/docker-magicmirror
  DOCKER_COMPOSE_PATH: magic-mirror-server/docker-compose.yml

on: 
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
    
      - name: Azure authentication
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App for Container'   
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.DOCKER_IMAGE }}
          configuration-file: ${{ env.DOCKER_COMPOSE_PATH }}
